```{r, setup, echo=F, results='hide', cache=F, error=T}
library(ggplot2)
library(data.table)

opts_chunk$set(results='hide',highlight=F, cache=F,error = F, tidy=F, echo=F, message=F, warning=F, comment=NA, external=F,split=F, dpi=320, dev='png', dev.args = list(type='cairo'))
opts_chunk$set(fig.path=paste0('outputs/figures/',prefix))

default_colors <-c('#3498db','#e74c3c','#009f06','#AA2255')
scale_colour_discrete <- function(...) scale_color_manual(values=default_colors, ...)

load(fname)

#source('first.R',local = TRUE)

# delay & threshold for conflict monitoring post-response conflict accumulator for error detection
CM_Delay = 6
CM_Threshold = .005

sim_data[[1]][[2]]<-sim_data[[1]][[2]][,c('congruency','accuracyf'):=list(droplevels(factor(congruency, levels=c('compatible','neutral','incompatible'), labels=c('Compatible','Neutral','Incompatible'))),factor(accuracy, labels=c('Errors','Correct')))]

dt_by_trial<-sim_data[[1]][[2]]
dt_by_trial[,ecr:=as.numeric(!is.na(error_corrections))]

energies_dt<-data.table(melt(sim_data[[1]][[3]]))

setnames(energies_dt,old=c('Var1', 'Var2' ,'value'),new= c('trialN','cycleN','energy'))
setorder(energies_dt,trialN,cycleN)

energies_dt<-merge(dt_by_trial, energies_dt, by='trialN')
setkeyv(energies_dt, c('trialN','cycleN'))

energies_dt[,resp_lockedN:=cycleN-respN]

cm_error_detections<-energies_dt[resp_lockedN>CM_Delay,list(respN,cycleN,cum_energy=cumsum(energy) ),by=trialN][cum_energy>CM_Threshold,list(cm_error_detectionN=cycleN[1], cm_error_detection_energy=cum_energy[1]*1000),by=trialN]
dt_by_trial<-merge(dt_by_trial,cm_error_detections,by='trialN', all.x=T)
dt_by_trial[, cm_esr:=as.numeric(!is.na(cm_error_detectionN))]
```

### Descriptives
```{r, results='asis'}
library(pander)
library(tables)
library(apastats)
panderOptions('round',2)
panderOptions('keep.trailing.zeros',T)
panderOptions('table.split.table',Inf)
panderOptions('table.split.cells',20)
pander(tabular(Heading('Congruence')*congruency + 1 ~ (Heading('Accuracy')*accuracy*Format(digits=2)+(Heading()*accuracyf + 1) *(Heading('RT')*RTs+Heading('RM ESR')*ecr*Format(f.round())+Heading('CM ESR')*cm_esr*Format(f.round())))*Heading()*mymean+1, data = dt_by_trial))
```

### Energies


```{r, fig.width=7 ,fig.height=5}
library(ggthemes)
library(grid)
library(gridExtra)
theme_set(theme_tufte(base_size = 12, base_family = "sans")+theme(axis.line=element_line(),axis.line.x=element_line(),axis.line.y=element_line(),panel.grid=element_line(colour = 'darkgray',size = I(4)),legend.title=element_text(size=rel(1)), strip.text=element_text(size=rel(1)), axis.text=element_text(size=rel(1)), axis.title=element_text(size=rel(1)), legend.position	='right', plot.title=element_text(size=rel(1)), text=element_text(size=12), legend.text=element_text(size=rel(1))))

grid.draw.np<-function (x){
  grid.newpage()
  grid.draw(x)
}

for (i in 1:length(sim_data)){
  energies <- sim_data[[i]][[3]]
  stimuli_sequence  <- sim_data[[i]][[2]]
  energies_dt<-data.table(melt(energies))
  
  setnames(energies_dt,old=c('Var1', 'Var2' ,'value'),new= c('trialN','cycleN','energy'))
  setorder(energies_dt,trialN,cycleN)
  energies_dt<-merge(stimuli_sequence, energies_dt, by='trialN')
  energies_dt[,resp_lockedN:=cycleN-respN]
  setkeyv(energies_dt,c('trialN','resp_lockedN'))
  energies_dt<-energies_dt[!is.na(accuracy)]
  
  fillup_dt<-data.table(expand.grid(trialN=1:nrow(stimuli_sequence), resp_lockedN=-50:50))
  fillup_dt[,energy_filler:=0]
  setkeyv(fillup_dt,c('trialN','resp_lockedN'))
  
  energies_dt<-energies_dt[fillup_dt, roll=T,rollends=c(T,T)]
  
  # energies_dt[,respN:=min(respN, na.rm=T),by=list(trialN)]
  # energies_dt[,respN:=min(respN, na.rm=T),by=list(trialN)]
  # # energies_dt[,rN:=rep(respN, each=54)]
  # energies_dt[,acc:=factor(rep(accuracy, each=54))]
  # energies_dt[,congr:=relevel(factor(rep(congruency, each=54)), ref='incompatible')]
  

  right_plots <- theme(axis.text.y=element_blank(), axis.title.y=element_blank())
  
  yscale<-function() scale_y_continuous(lim=c(0,0.035), breaks=seq(0,.03,.01))
  
  top_plots <- theme(axis.text.x=element_blank())
  
  all_plots_labs<-labs(x=NULL, y='Conflict', color='Congruence', linetype='Accuracy')
  

  
  p1 <- qplot(data=data.frame(energies_dt[!is.na(respN),list(energy=mymean(energy)), by=list(resp_lockedN,congruency,accuracyf)]), x=resp_lockedN,y=energy, linetype=accuracyf, color=congruency, geom='line', size=I(1))+ ggtitle('Response-locked')+scale_x_continuous(breaks=seq(-50,50,by=25))+top_plots+yscale()+all_plots_labs
  
  p2 <- qplot(data=data.frame(energies_dt[!is.na(respN),list(energy=mymean(energy)), by=list(cycleN,congruency,accuracyf)]), x=cycleN,y=energy, linetype=accuracyf, color=congruency, geom='line', size=I(1)) + ggtitle('Stimulus-locked') + right_plots + top_plots+yscale()+scale_x_continuous(breaks=seq(0,50,by=10))+all_plots_labs
  
  p3 <- qplot(data=data.frame(energies_dt[!is.na(respN),list(energy=mymean(energy)), by=list(resp_lockedN,accuracyf)]), x=resp_lockedN,y=energy, linetype=accuracyf,  geom='line', size=I(1))+scale_x_continuous(breaks=seq(-50,50,by=25))+yscale()+all_plots_labs
  
  p4 <- qplot(data=data.frame(energies_dt[!is.na(respN),list(energy=mymean(energy)), by=list(cycleN,accuracyf)]), x=cycleN,y=energy, linetype=accuracyf,  geom='line', size=I(1))+right_plots+yscale()+scale_x_continuous(breaks=seq(0,50,by=10))+all_plots_labs
  
  assign(paste('plot', i, '1', sep="_"), p1)
  assign(paste('plot', i, '2', sep="_"), p2)
  assign(paste('plot', i, '3', sep="_"), p3)
  assign(paste('plot', i, '4', sep="_"), p4)
  assign(paste('plot', i, 'c', sep="_"), rbind.gtable(cbind.gtable(ggplotGrob(p1+theme(legend.position='none')),ggplotGrob(p2)),cbind.gtable(ggplotGrob(p3+theme(legend.position='none')),ggplotGrob(p4))))
  
}

grid.draw.np(plot_1_c)

#ggsave('outputs/2_flanker_sim.png', plot_1_c, dpi=320, width=9, height=7,limitsize = F, type = "cairo-png")
```
